### ISSUE TITLE
Please The image doesn't load on my device, it throws  the below exception

### ISSUE THREAD

**Issue by wisdomspine** [zesage/flutter_earth#4]
════════ Exception caught by image resource service ════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack
#0      _futurize (dart:ui/painting.dart:4856:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:4724:12)
#2      instantiateImageCodec (dart:ui/painting.dart:1721:60)
<asynchronous suspension>
#3      PaintingBinding.instantiateImageCodec
package:flutter/…/painting/binding.dart:97
...
Image provider: NetworkImage("https://www.google.com/maps/@-19.088885,4.9352279,9036909m/data=!3m1!1e3", scale: 1.0)
Image key: NetworkImage("https://www.google.com/maps/@-19.088885,4.9352279,9036909m/data=!3m1!1e3", scale: 1.0)

**Comment by kesamani** [comment]
i also facing same issue please support
